
platform :ios, '9.0'
project 'WalletDemo.xcodeproj'

target :WalletDemo do


pod 'SDWebImage', '4.3.3'
pod 'MBProgressHUD+BWMExtension', '1.0.1'
pod 'MJRefresh', '3.1.15.3'
pod 'Masonry', '1.1.0'
pod 'YYCategories', '1.0.4'
pod 'BButton','4.0.2'
pod 'QMUIKit', '2.6.1'
pod 'FMDB', '2.7.2'
pod 'JPush', '3.0.8'
pod 'libextobjc/EXTScope', '0.4.1'
pod 'Bugly', '2.5.0'

pod 'MBRWallet'

end
