
platform :ios, '9.0'
project 'WalletDemo.xcodeproj'

target :WalletDemo do


pod 'SDWebImage', '4.3.3'
pod 'MBProgressHUD+BWMExtension', '1.0.1'
pod 'MJRefresh', '3.1.15.3'
pod 'Masonry', '1.1.0'
pod 'YYCategories', '1.0.4'
pod 'QMUIKit', '2.6.1'

pod 'MBRWallet'
#pod 'MBRWallet', :path => '../MBRWallet.podspec'
#pod 'MBRWallet', :path => '../../../pay/MBRWallet-iOS/MBRWallet.podspec'


end
